# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180116_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FITSRawImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits_image', models.FileField(upload_to='fits_images/', verbose_name='FITS image')),
            ],
        ),
        migrations.AddField(
            model_name='galaxyimage',
            name='original_fits_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FITSRawImage'),
        ),
    ]
