# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180201_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyimage',
            name='id_splus',
            field=models.BigIntegerField(default=1, verbose_name='ID splus'),
            preserve_default=False,
        ),
    ]
