# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galaxyimage_id_splus'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyimage',
            name='tutorial_image',
            field=models.BooleanField(default=False, verbose_name='Usar no tutorial'),
        ),
    ]
