# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_galaxyimage_tutorial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyimage',
            name='field_number',
            field=models.IntegerField(default=0, verbose_name='Campo'),
        ),
        migrations.AlterField(
            model_name='galaxyimage',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
