# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180206_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyimage',
            name='is_consensus',
            field=models.BooleanField(default=False, verbose_name='Consenso'),
        ),
        migrations.AlterField(
            model_name='galaxyclassification',
            name='galaxy_type',
            field=models.IntegerField(choices=[(0, 'Espiral'), (10, 'Elíptica'), (20, 'Irregular'), (30, 'Outra')], verbose_name='Galaxy type'),
        ),
    ]
