# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180206_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_tutorial',
            field=models.BooleanField(default=False, verbose_name='Fez tutorial'),
        ),
    ]
