# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180206_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyimage',
            name='coord_dec',
            field=models.CharField(default='', max_length=14, verbose_name='DEC'),
        ),
        migrations.AddField(
            model_name='galaxyimage',
            name='coord_ra',
            field=models.CharField(default='', max_length=14, verbose_name='RA'),
        ),
    ]
